# Generated by Django 5.2.4 on 2025-09-08 10:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='User email address', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='User phone number', max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='User date of birth', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/')),
                ('address', models.TextField(blank=True, help_text='User address', null=True)),
                ('city', models.CharField(blank=True, help_text='User city', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='User country', max_length=100, null=True)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Whether email is verified')),
                ('is_phone_verified', models.BooleanField(default=False, help_text='Whether phone is verified')),
                ('is_active', models.BooleanField(default=True, help_text='Whether user account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('password_reset_token', models.CharField(blank=True, help_text='Password reset token', max_length=255, null=True)),
                ('password_reset_expires', models.DateTimeField(blank=True, help_text='Password reset token expiry', null=True)),
                ('email_verification_token', models.CharField(blank=True, help_text='Email verification token', max_length=255, null=True)),
                ('email_verification_expires', models.DateTimeField(blank=True, help_text='Email verification token expiry', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, help_text='User job title', max_length=100, null=True)),
                ('company', models.CharField(blank=True, help_text='User company', max_length=100, null=True)),
                ('department', models.CharField(blank=True, help_text='User department', max_length=100, null=True)),
                ('timezone', models.CharField(default='UTC', help_text='User timezone', max_length=50)),
                ('language', models.CharField(default='en', help_text='User preferred language', max_length=10)),
                ('notification_preferences', models.JSONField(default=dict, help_text='User notification preferences')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update timestamp')),
                ('user', models.OneToOneField(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Password reset token', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('is_used', models.BooleanField(default=False, help_text='Whether reset token has been used')),
                ('is_expired', models.BooleanField(default=False, help_text='Whether reset token has expired')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Request creation timestamp')),
                ('expires_at', models.DateTimeField(help_text='Token expiry timestamp')),
                ('used_at', models.DateTimeField(blank=True, help_text='When token was used', null=True)),
                ('user', models.ForeignKey(help_text='User requesting password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'db_table': 'password_reset_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_used'], name='password_re_user_id_1e693e_idx'), models.Index(fields=['token'], name='password_re_token_625fe7_idx'), models.Index(fields=['expires_at'], name='password_re_expires_96f32e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(help_text='JWT session token', max_length=255, unique=True)),
                ('refresh_token', models.CharField(help_text='JWT refresh token', max_length=255, unique=True)),
                ('device_info', models.JSONField(default=dict, help_text='Device information (browser, OS, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the session', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('access_token_expires', models.DateTimeField(help_text='Access token expiry time')),
                ('refresh_token_expires', models.DateTimeField(help_text='Refresh token expiry time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether session is active')),
                ('is_revoked', models.BooleanField(default=False, help_text='Whether session is revoked')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Session creation timestamp')),
                ('last_used_at', models.DateTimeField(auto_now=True, help_text='Last session usage timestamp')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Session revocation timestamp', null=True)),
                ('user', models.ForeignKey(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'), models.Index(fields=['session_token'], name='user_sessio_session_baddb8_idx'), models.Index(fields=['refresh_token'], name='user_sessio_refresh_006d95_idx'), models.Index(fields=['access_token_expires'], name='user_sessio_access__4ee713_idx')],
            },
        ),
    ]
