# Generated by Django 5.2.4 on 2025-09-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(db_index=True, help_text='Client identifier code (can be duplicate across different clients)', max_length=20),
        ),
    ]
