# Generated by Django 5.2.4 on 2025-08-31 16:00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='post_close_analysis',
            field=models.JSONField(default=dict, help_text='Post-close analysis data'),
        ),
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='fs_line_closing',
            field=models.JSONField(default=dict, help_text='Financial statement line closing data'),
        ),
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='user_closing',
            field=models.JSONField(default=dict, help_text='User closing patterns'),
        ),
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='month_end_patterns',
            field=models.JSONField(default=dict, help_text='Month-end closing patterns'),
        ),
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='closing_window_analysis',
            field=models.JSONField(default=dict, help_text='Closing window analysis data'),
        ),
    ]
