# Generated by Django 5.2.4 on 2025-09-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of file content for duplicate detection', max_length=64),
        ),
    ]
