# Generated by Django 5.2.4 on 2025-07-30 07:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingEntriesAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_date', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
                ('analysis_type', models.CharField(default='closing_entries_analysis', help_text='Type of analysis performed', max_length=50)),
                ('analysis_version', models.CharField(default='1.0.0', help_text='Version of analysis algorithm', max_length=20)),
                ('analysis_info', models.JSONField(default=dict, help_text='General analysis information (total transactions, closing entries, etc.)')),
                ('closing_entries', models.JSONField(default=list, help_text='List of closing entries detected')),
                ('post_close_analysis', models.JSONField(default=dict, help_text='Post-close flag analysis')),
                ('fs_line_closing', models.JSONField(default=dict, help_text='Closing entries by financial statement line')),
                ('user_closing', models.JSONField(default=dict, help_text='Closing entries by user')),
                ('month_end_patterns', models.JSONField(default=dict, help_text='Month-end activity patterns')),
                ('closing_window_analysis', models.JSONField(default=dict, help_text='Analysis of closing windows')),
                ('risk_assessment', models.JSONField(default=dict, help_text='Risk assessment for closing entries')),
                ('chart_data', models.JSONField(default=dict, help_text='Chart data for visualizations')),
                ('export_data', models.JSONField(default=list, help_text='Export-ready data')),
                ('processing_duration', models.FloatField(blank=True, help_text='Processing duration in seconds', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_file', models.ForeignKey(help_text='Reference to the data file', on_delete=django.db.models.deletion.CASCADE, related_name='closing_entries_analyses', to='core.datafile')),
                ('processing_job', models.ForeignKey(blank=True, help_text='Reference to the processing job that generated this analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_entries_results', to='core.fileprocessingjob')),
            ],
            options={
                'db_table': 'closing_entries_analysis_results',
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['data_file', 'analysis_date'], name='closing_ent_data_fi_8db6c5_idx'), models.Index(fields=['analysis_type', 'status'], name='closing_ent_analysi_4bf232_idx'), models.Index(fields=['processing_job', 'status'], name='closing_ent_process_326d6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnusualDaysAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_date', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
                ('analysis_type', models.CharField(default='unusual_days_analysis', help_text='Type of analysis performed', max_length=50)),
                ('analysis_version', models.CharField(default='1.0.0', help_text='Version of analysis algorithm', max_length=20)),
                ('analysis_info', models.JSONField(default=dict, help_text='General analysis information (total transactions, weekend postings, etc.)')),
                ('weekend_postings', models.JSONField(default=list, help_text='List of weekend postings (Friday/Saturday)')),
                ('day_of_week_activity', models.JSONField(default=dict, help_text='Activity patterns by day of week')),
                ('user_day_patterns', models.JSONField(default=list, help_text='User posting patterns by day of week')),
                ('fs_line_day_patterns', models.JSONField(default=list, help_text='FS line activity by day of week')),
                ('unusual_days', models.JSONField(default=list, help_text='List of unusual day patterns detected')),
                ('risk_assessment', models.JSONField(default=dict, help_text='Risk assessment for unusual days')),
                ('chart_data', models.JSONField(default=dict, help_text='Chart data for visualizations')),
                ('export_data', models.JSONField(default=list, help_text='Export-ready data')),
                ('processing_duration', models.FloatField(blank=True, help_text='Processing duration in seconds', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_file', models.ForeignKey(help_text='Reference to the data file', on_delete=django.db.models.deletion.CASCADE, related_name='unusual_days_analyses', to='core.datafile')),
                ('processing_job', models.ForeignKey(blank=True, help_text='Reference to the processing job that generated this analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unusual_days_results', to='core.fileprocessingjob')),
            ],
            options={
                'db_table': 'unusual_days_analysis_results',
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['data_file', 'analysis_date'], name='unusual_day_data_fi_341034_idx'), models.Index(fields=['analysis_type', 'status'], name='unusual_day_analysi_4e9ea2_idx'), models.Index(fields=['processing_job', 'status'], name='unusual_day_process_f9d427_idx')],
            },
        ),
    ]
