# Generated by Django 5.2.4 on 2025-08-03 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_closingentriesanalysisresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapglposting',
            name='holiday_analysis_details',
            field=models.JSONField(default=dict, help_text='Detailed holiday analysis results'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='holiday_name',
            field=models.CharField(blank=True, help_text='Name of the holiday', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='holiday_risk_score',
            field=models.FloatField(default=0.0, help_text='Risk score for holiday detection (0-100)'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='holiday_type',
            field=models.CharField(blank=True, help_text='Type of holiday (Public holiday, Observance, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='is_holiday_posting',
            field=models.BooleanField(default=False, help_text='Flagged as holiday posting'),
        ),
        migrations.CreateModel(
            name='HolidayAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_date', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
                ('analysis_type', models.CharField(default='holiday_analysis', help_text='Type of analysis performed', max_length=50)),
                ('analysis_version', models.CharField(default='1.0.0', help_text='Version of analysis algorithm', max_length=20)),
                ('analysis_info', models.JSONField(default=dict, help_text='General analysis information (total transactions, holiday postings, etc.)')),
                ('holiday_postings', models.JSONField(default=list, help_text='List of transactions posted on holidays')),
                ('holiday_by_fs_line', models.JSONField(default=list, help_text='Holiday postings grouped by financial statement line')),
                ('holiday_by_account', models.JSONField(default=list, help_text='Holiday postings grouped by GL account')),
                ('holiday_by_user', models.JSONField(default=list, help_text='Holiday postings grouped by user')),
                ('holiday_by_holiday_type', models.JSONField(default=dict, help_text='Holiday postings grouped by holiday type')),
                ('gl_activity_by_holiday', models.JSONField(default=dict, help_text='GL activity patterns by holiday')),
                ('audit_recommendations', models.JSONField(default=dict, help_text='Audit recommendations and priorities')),
                ('compliance_assessment', models.JSONField(default=dict, help_text='Compliance risk assessment')),
                ('financial_statement_impact', models.JSONField(default=dict, help_text='Financial statement impact analysis')),
                ('chart_data', models.JSONField(default=dict, help_text='Chart data for visualizations')),
                ('export_data', models.JSONField(default=list, help_text='Export-ready data')),
                ('processing_duration', models.FloatField(blank=True, help_text='Processing duration in seconds', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_file', models.ForeignKey(help_text='Reference to the data file', on_delete=django.db.models.deletion.CASCADE, related_name='holiday_analyses', to='core.datafile')),
                ('processing_job', models.ForeignKey(blank=True, help_text='Reference to the processing job that generated this analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_results', to='core.fileprocessingjob')),
            ],
            options={
                'db_table': 'holiday_analysis_results',
                'ordering': ['-analysis_date'],
                'indexes': [models.Index(fields=['data_file', 'analysis_date'], name='holiday_ana_data_fi_dd9f9f_idx'), models.Index(fields=['analysis_type', 'status'], name='holiday_ana_analysi_f7e58a_idx'), models.Index(fields=['processing_job', 'created_at'], name='holiday_ana_process_fe2c53_idx')],
            },
        ),
    ]
