# Generated by Django 5.2.4 on 2025-09-09 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_datafile_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='gl_account',
            field=models.CharField(blank=True, help_text='G/L Account (legacy field)', max_length=20),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='gl_account',
            field=models.CharField(db_index=True, help_text='G/L Account (legacy field)', max_length=10),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='gl_account',
            field=models.CharField(help_text='G/L Account (legacy field)', max_length=10),
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(db_index=True, help_text='GL Account Code', max_length=10, unique=True)),
                ('account_name', models.CharField(help_text='GL Account Name', max_length=200)),
                ('account_type', models.CharField(blank=True, help_text='Account Type', max_length=50)),
                ('account_subtype', models.CharField(blank=True, help_text='Account Subtype', max_length=50)),
                ('company_code', models.CharField(blank=True, help_text='Company Code', max_length=10)),
                ('profit_center', models.CharField(blank=True, help_text='Profit Center', max_length=10)),
                ('cost_center', models.CharField(blank=True, help_text='Cost Center', max_length=10)),
                ('financial_statement_category', models.CharField(blank=True, help_text='Financial Statement Category', max_length=50)),
                ('balance_sheet_category', models.CharField(blank=True, help_text='Balance Sheet Category', max_length=50)),
                ('income_statement_category', models.CharField(blank=True, help_text='Income Statement Category', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is Account Active')),
                ('currency', models.CharField(default='SAR', help_text='Account Currency', max_length=3)),
                ('engagement_id', models.CharField(blank=True, help_text='Engagement ID where this account was first seen', max_length=100)),
                ('client_name', models.CharField(blank=True, help_text='Client Name', max_length=255)),
            ],
            options={
                'db_table': 'gl_accounts',
                'ordering': ['account_code'],
                'indexes': [models.Index(fields=['account_code'], name='gl_accounts_account_66b326_idx'), models.Index(fields=['account_name'], name='gl_accounts_account_38b57f_idx'), models.Index(fields=['company_code', 'account_code'], name='gl_accounts_company_6e1b7e_idx'), models.Index(fields=['engagement_id', 'account_code'], name='gl_accounts_engagem_99d848_idx'), models.Index(fields=['financial_statement_category'], name='gl_accounts_financi_710514_idx'), models.Index(fields=['is_active'], name='gl_accounts_is_acti_58f55e_idx')],
            },
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='gl_account_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to GL Account master record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chart_of_accounts', to='core.glaccount'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='gl_account_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to GL Account master record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_postings', to='core.glaccount'),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='gl_account_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to GL Account master record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trial_balances', to='core.glaccount'),
        ),
    ]
