# Generated by Django 5.2.4 on 2025-09-01 10:35:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_closing_entries_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranalysisresult',
            name='breakdowns',
            field=models.JSONField(default=dict, help_text='Various breakdowns including ML insights'),
        ),
    ]
