# Generated by Django 5.2.4 on 2025-09-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_code_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='adj_reclas',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Adjustments/Reclassifications', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='fin_q1_amount',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Final Q1 Amount', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='q1_amount',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Q1 Amount', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Closing Balance from TB', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Opening Balance from TB', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='tb_credit',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Credit Amount from TB (optional)', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='glaccount',
            name='tb_debit',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Debit Amount from TB (optional)', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='closing_balance',
            field=models.DecimalField(decimal_places=10, help_text='Closing Balance (REQUIRED for each account)', max_digits=30),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Credit Amount (OPTIONAL)', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Debit Amount (OPTIONAL)', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='opening_balance',
            field=models.DecimalField(decimal_places=10, help_text='Opening Balance (REQUIRED for each account)', max_digits=30),
        ),
    ]
