# Generated by Django 5.2.4 on 2025-08-03 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_holiday_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleBasedModelTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the training session')),
                ('model_type', models.CharField(default='rule_based', help_text='Type of model trained', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of transactions used for training')),
                ('training_data_date_range', models.JSONField(default=dict, help_text='Date range of training data')),
                ('training_results', models.JSONField(default=dict, help_text='Detailed training results for each rule type')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Performance metrics from training')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When training started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('training_duration', models.FloatField(default=0.0, help_text='Training duration in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Training status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
            ],
            options={
                'db_table': 'rule_based_model_training',
                'ordering': ['-started_at'],
            },
        ),
    ]
