# Generated by Django 5.2.4 on 2025-09-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chartofaccount_gl_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprocessingjob',
            name='job_type',
            field=models.CharField(choices=[('GL_PROCESSING', 'GL Data Processing'), ('ANALYSIS', 'Analysis'), ('COMPLETENESS', 'Completeness Test')], default='GL_PROCESSING', help_text='Type of processing job', max_length=20),
        ),
    ]
