# Generated by Django 5.2.4 on 2025-09-01 11:30:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_breakdowns_to_user_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='backdatedanalysisresult',
            name='breakdowns',
            field=models.JSONField(default=dict, help_text='Various breakdowns including ML insights'),
        ),
        migrations.AddField(
            model_name='unusualdaysanalysisresult',
            name='breakdowns',
            field=models.JSONField(default=dict, help_text='Various breakdowns including ML insights'),
        ),
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='breakdowns',
            field=models.JSONField(default=dict, help_text='Various breakdowns including ML insights'),
        ),
        migrations.AddField(
            model_name='holidayanalysisresult',
            name='breakdowns',
            field=models.JSONField(default=dict, help_text='Various breakdowns including ML insights'),
        ),
    ]
