# Generated by Django 5.2.4 on 2025-09-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_increase_decimal_places'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datafile',
            unique_together=set(),
        ),
    ]
