# Generated by Django 5.2.4 on 2025-08-04 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_rule_based_model_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackdatedAnalysisModelTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the training session')),
                ('model_type', models.CharField(default='backdated_analysis', help_text='Type of model trained', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of transactions used for training')),
                ('training_data_date_range', models.JSONField(default=dict, help_text='Date range of training data')),
                ('training_results', models.JSONField(default=dict, help_text='Detailed training results for backdated detection')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Performance metrics from training')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When training started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('training_duration', models.FloatField(default=0.0, help_text='Training duration in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Training status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
            ],
            options={
                'db_table': 'backdated_analysis_model_training',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ClosingEntriesAnalysisModelTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the training session')),
                ('model_type', models.CharField(default='closing_entries_analysis', help_text='Type of model trained', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of transactions used for training')),
                ('training_data_date_range', models.JSONField(default=dict, help_text='Date range of training data')),
                ('training_results', models.JSONField(default=dict, help_text='Detailed training results for closing entries detection')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Performance metrics from training')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When training started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('training_duration', models.FloatField(default=0.0, help_text='Training duration in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Training status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
            ],
            options={
                'db_table': 'closing_entries_analysis_model_training',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateAnalysisModelTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the training session')),
                ('model_type', models.CharField(default='duplicate_analysis', help_text='Type of model trained', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of transactions used for training')),
                ('training_data_date_range', models.JSONField(default=dict, help_text='Date range of training data')),
                ('training_results', models.JSONField(default=dict, help_text='Detailed training results for duplicate detection')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Performance metrics from training')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When training started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('training_duration', models.FloatField(default=0.0, help_text='Training duration in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Training status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
            ],
            options={
                'db_table': 'duplicate_analysis_model_training',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayAnalysisModelTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the training session')),
                ('model_type', models.CharField(default='holiday_analysis', help_text='Type of model trained', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of transactions used for training')),
                ('training_data_date_range', models.JSONField(default=dict, help_text='Date range of training data')),
                ('training_results', models.JSONField(default=dict, help_text='Detailed training results for holiday detection')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Performance metrics from training')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When training started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('training_duration', models.FloatField(default=0.0, help_text='Training duration in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Training status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
            ],
            options={
                'db_table': 'holiday_analysis_model_training',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OverallRiskAnalysisModelTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the training session')),
                ('model_type', models.CharField(default='overall_risk_analysis', help_text='Type of model trained', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of transactions used for training')),
                ('training_data_date_range', models.JSONField(default=dict, help_text='Date range of training data')),
                ('training_results', models.JSONField(default=dict, help_text='Detailed training results for overall risk analysis')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Performance metrics from training')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When training started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('training_duration', models.FloatField(default=0.0, help_text='Training duration in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Training status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
            ],
            options={
                'db_table': 'overall_risk_analysis_model_training',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UnusualDaysAnalysisModelTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the training session')),
                ('model_type', models.CharField(default='unusual_days_analysis', help_text='Type of model trained', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of transactions used for training')),
                ('training_data_date_range', models.JSONField(default=dict, help_text='Date range of training data')),
                ('training_results', models.JSONField(default=dict, help_text='Detailed training results for unusual days detection')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Performance metrics from training')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When training started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('training_duration', models.FloatField(default=0.0, help_text='Training duration in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Training status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
            ],
            options={
                'db_table': 'unusual_days_analysis_model_training',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnalysisModelTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(help_text='Name of the training session', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the training session')),
                ('model_type', models.CharField(default='user_analysis', help_text='Type of model trained', max_length=50)),
                ('training_data_size', models.IntegerField(default=0, help_text='Number of transactions used for training')),
                ('training_data_date_range', models.JSONField(default=dict, help_text='Date range of training data')),
                ('training_results', models.JSONField(default=dict, help_text='Detailed training results for user anomaly detection')),
                ('performance_metrics', models.JSONField(default=dict, help_text='Performance metrics from training')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When training started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When training completed', null=True)),
                ('training_duration', models.FloatField(default=0.0, help_text='Training duration in seconds')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRAINING', 'Training'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Training status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if training failed')),
            ],
            options={
                'db_table': 'user_analysis_model_training',
                'ordering': ['-started_at'],
            },
        ),
    ]
