# Generated by Django 5.2.4 on 2025-09-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_job_type_to_file_processing_job'),
    ]

    operations = [
    ]
