# Generated by Django 5.2.4 on 2025-09-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_breakdowns_to_all_analysis_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayanalysisresult',
            name='breakdowns',
            field=models.JSONField(default=dict, help_text='Various breakdowns including ML insights'),
        ),
    ]
