# Generated by Django 5.2.4 on 2025-09-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_datafile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapglposting',
            name='amount_transaction_currency',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Amount in transaction currency', max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='asset_number',
            field=models.CharField(blank=True, help_text='Asset Number', max_length=20),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='business_area',
            field=models.CharField(blank=True, help_text='Business Area', max_length=10),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='company_code',
            field=models.CharField(blank=True, help_text='Company Code', max_length=10),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost Center', max_length=10),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='document_header_text',
            field=models.CharField(blank=True, help_text='Document Header Text', max_length=200),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='fiscal_period',
            field=models.IntegerField(blank=True, help_text='Fiscal Period', null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='order_number',
            field=models.CharField(blank=True, help_text='Order Number', max_length=20),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='partner_business_area',
            field=models.CharField(blank=True, help_text='Partner Business Area', max_length=10),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='posting_key',
            field=models.CharField(blank=True, help_text='Posting Key', max_length=10),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='reference_document',
            field=models.CharField(blank=True, help_text='Reference Document', max_length=20),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='sub_number',
            field=models.CharField(blank=True, help_text='Sub Number', max_length=10),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Transaction currency code', max_length=3),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='wbs_element',
            field=models.CharField(blank=True, help_text='WBS Element', max_length=20),
        ),
    ]
