# Generated by Django 5.2.4 on 2025-09-10 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_job_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapglposting',
            name='document_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SAP Document Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='document_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Document Type', max_length=10),
        ),
        migrations.CreateModel(
            name='SAPGLPostingError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_type', models.CharField(help_text='Type of error that occurred', max_length=100)),
                ('error_message', models.TextField(help_text='Detailed error message')),
                ('error_timestamp', models.DateTimeField(auto_now_add=True, help_text='When the error occurred')),
                ('raw_data', models.JSONField(help_text='Original data that failed to process')),
                ('batch_number', models.IntegerField(help_text='Batch number where error occurred')),
                ('record_index', models.IntegerField(help_text='Index of record within the batch')),
                ('data_file', models.ForeignKey(help_text='Reference to the uploaded file', on_delete=django.db.models.deletion.CASCADE, to='core.datafile')),
            ],
            options={
                'db_table': 'core_sapglposting_error',
                'indexes': [models.Index(fields=['data_file', 'error_timestamp'], name='core_sapglp_data_fi_8eec34_idx'), models.Index(fields=['error_type'], name='core_sapglp_error_t_fead4c_idx')],
            },
        ),
    ]
