# Generated by Django 5.2.4 on 2025-08-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_backdatedanalysismodeltraining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscoringdocument',
            name='critical_risk_transactions',
            field=models.IntegerField(default=0, help_text='Number of critical-risk transactions'),
        ),
    ]
