# Generated by Django 5.2.4 on 2025-09-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sapglposting_amount_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='adj_reclas',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Adjustments/Reclassifications', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='fin_q1_amount',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Final Q1 Amount', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='q1_amount',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Q1 Amount', max_digits=30, null=True),
        ),
    ]
