# Generated by Django 5.2.4 on 2025-09-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_decimal_places_chart_of_accounts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('data_file', 'account', 'company')},
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['data_file', 'account', 'company'], name='chart_of_ac_data_fi_d33df0_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['company'], name='chart_of_ac_company_a666fd_idx'),
        ),
    ]
