# Generated by Django 5.2.4 on 2025-08-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_riskscoringdocument_critical_risk_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='audit_recommendations',
            field=models.JSONField(default=dict, help_text='Audit recommendations and priorities'),
        ),
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='compliance_assessment',
            field=models.JSONField(default=dict, help_text='Compliance risk assessment'),
        ),
        migrations.AddField(
            model_name='closingentriesanalysisresult',
            name='financial_statement_impact',
            field=models.JSONField(default=dict, help_text='Financial statement impact analysis'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='closing_entry_analysis_details',
            field=models.JSONField(default=dict, help_text='Detailed closing entry analysis results'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='closing_entry_risk_score',
            field=models.FloatField(default=0.0, help_text='Risk score for closing entry detection (0-100)'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='closing_entry_type',
            field=models.CharField(blank=True, help_text='Type of closing entry', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='is_closing_entry',
            field=models.BooleanField(default=False, help_text='Flagged as closing entry'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='is_unusual_days_posting',
            field=models.BooleanField(default=False, help_text='Flagged as unusual days posting'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='is_user_anomaly',
            field=models.BooleanField(default=False, help_text='Flagged as user anomaly'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='unusual_days_analysis_details',
            field=models.JSONField(default=dict, help_text='Detailed unusual days analysis results'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='unusual_days_risk_score',
            field=models.FloatField(default=0.0, help_text='Risk score for unusual days detection (0-100)'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='unusual_days_type',
            field=models.CharField(blank=True, help_text='Type of unusual day (weekend, holiday, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='user_anomaly_analysis_details',
            field=models.JSONField(default=dict, help_text='Detailed user anomaly analysis results'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='user_anomaly_risk_score',
            field=models.FloatField(default=0.0, help_text='Risk score for user anomaly detection (0-100)'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='user_anomaly_type',
            field=models.CharField(blank=True, help_text='Type of user anomaly', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unusualdaysanalysisresult',
            name='audit_recommendations',
            field=models.JSONField(default=dict, help_text='Audit recommendations and priorities'),
        ),
        migrations.AddField(
            model_name='unusualdaysanalysisresult',
            name='compliance_assessment',
            field=models.JSONField(default=dict, help_text='Compliance risk assessment'),
        ),
        migrations.AddField(
            model_name='unusualdaysanalysisresult',
            name='financial_statement_impact',
            field=models.JSONField(default=dict, help_text='Financial statement impact analysis'),
        ),
        migrations.AddField(
            model_name='useranalysisresult',
            name='audit_recommendations',
            field=models.JSONField(default=dict, help_text='Audit recommendations and priorities'),
        ),
        migrations.AddField(
            model_name='useranalysisresult',
            name='compliance_assessment',
            field=models.JSONField(default=dict, help_text='Compliance risk assessment'),
        ),
        migrations.AddField(
            model_name='useranalysisresult',
            name='financial_statement_impact',
            field=models.JSONField(default=dict, help_text='Financial statement impact analysis'),
        ),
    ]
