# Generated by Django 5.2.4 on 2025-09-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sapglposting_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapglposting',
            name='amount_local_currency',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=10, help_text='Amount in local currency (flexible precision)', max_digits=30, null=True),
        ),
    ]
