# Generated by Django 5.2.4 on 2025-09-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_company_to_coa_unique_constraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='chart_of_ac_data_fi_d33df0_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('data_file', 'account', 'cost_center')},
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['data_file', 'account', 'cost_center'], name='chart_of_ac_data_fi_5d57b4_idx'),
        ),
    ]
