# Generated by Django 5.2.4 on 2025-09-11 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sapglposting_amount_local_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICompletenessModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(help_text='Name of the AI model', max_length=100)),
                ('model_version', models.CharField(default='1.0.0', help_text='Version of the model', max_length=20)),
                ('client_name', models.CharField(blank=True, help_text='Client-specific model (empty for general model)', max_length=255)),
                ('model_type', models.CharField(choices=[('COMPLETENESS_PREDICTOR', 'Completeness Pass/Fail Predictor'), ('SCORE_ESTIMATOR', 'Completeness Score Estimator'), ('STEP_PREDICTOR', 'Individual Step Success Predictor'), ('CLIENT_PATTERN_LEARNER', 'Client-Specific Completeness Pattern Learning')], help_text='Type of AI model', max_length=30)),
                ('training_data_size', models.IntegerField(help_text='Number of completeness tests used for training')),
                ('training_accuracy', models.FloatField(blank=True, help_text='Model training accuracy (0-100%)', null=True)),
                ('validation_accuracy', models.FloatField(blank=True, help_text='Model validation accuracy (0-100%)', null=True)),
                ('test_accuracy', models.FloatField(blank=True, help_text='Model test accuracy (0-100%)', null=True)),
                ('feature_set', models.JSONField(default=list, help_text='List of features used for training')),
                ('model_parameters', models.JSONField(default=dict, help_text='Model hyperparameters and configuration')),
                ('feature_importance', models.JSONField(default=dict, help_text='Feature importance scores')),
                ('status', models.CharField(choices=[('TRAINING', 'Training in Progress'), ('TRAINED', 'Training Completed'), ('DEPLOYED', 'Deployed for Predictions'), ('FAILED', 'Training Failed'), ('DEPRECATED', 'Model Deprecated')], default='TRAINING', max_length=20)),
                ('training_started_at', models.DateTimeField(blank=True, null=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('training_duration', models.FloatField(blank=True, help_text='Training duration in seconds', null=True)),
                ('predictions_made', models.IntegerField(default=0, help_text='Total predictions made by this model')),
                ('correct_predictions', models.IntegerField(default=0, help_text='Number of correct predictions')),
                ('prediction_accuracy', models.FloatField(blank=True, help_text='Real-world prediction accuracy', null=True)),
                ('model_file_path', models.CharField(blank=True, help_text='Path to saved model file', max_length=500)),
                ('scaler_file_path', models.CharField(blank=True, help_text='Path to feature scaler file', max_length=500)),
                ('client_patterns', models.JSONField(default=dict, help_text='Learned patterns specific to client')),
                ('optimization_insights', models.JSONField(default=dict, help_text='Process optimization insights')),
            ],
            options={
                'db_table': 'ai_completeness_models',
                'ordering': ['-training_completed_at'],
                'indexes': [models.Index(fields=['model_type', 'status'], name='ai_complete_model_t_d7d31f_idx'), models.Index(fields=['client_name', 'model_type'], name='ai_complete_client__78dead_idx'), models.Index(fields=['status', 'prediction_accuracy'], name='ai_complete_status_39713d_idx'), models.Index(fields=['training_completed_at'], name='ai_complete_trainin_215d70_idx')],
                'unique_together': {('model_name', 'model_version', 'client_name')},
            },
        ),
        migrations.CreateModel(
            name='CompletenessAIPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prediction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('prediction_confidence', models.FloatField(help_text='Confidence score of the prediction (0-100%)')),
                ('predicted_completeness_score', models.FloatField(help_text='Predicted completeness score (0-100%)')),
                ('predicted_status', models.CharField(help_text='Predicted overall status (PASS/FAIL)', max_length=20)),
                ('predicted_step_results', models.JSONField(default=dict, help_text='Predicted results for each completeness step')),
                ('predicted_processing_time', models.FloatField(blank=True, help_text='Predicted processing time in seconds', null=True)),
                ('input_features', models.JSONField(default=dict, help_text='Features extracted from file for prediction')),
                ('actual_completeness_score', models.FloatField(blank=True, help_text='Actual completeness score', null=True)),
                ('actual_status', models.CharField(blank=True, help_text='Actual overall status', max_length=20)),
                ('actual_processing_time', models.FloatField(blank=True, help_text='Actual processing time', null=True)),
                ('score_accuracy', models.FloatField(blank=True, help_text='Accuracy of score prediction (0-100%)', null=True)),
                ('status_correct', models.BooleanField(blank=True, help_text='Whether status prediction was correct', null=True)),
                ('step_accuracy', models.FloatField(blank=True, help_text='Accuracy of step predictions (0-100%)', null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.aicompletenessmodel')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='core.datafile')),
            ],
            options={
                'db_table': 'completeness_ai_predictions',
                'ordering': ['-prediction_timestamp'],
                'indexes': [models.Index(fields=['data_file', 'prediction_timestamp'], name='completenes_data_fi_d6d64d_idx'), models.Index(fields=['ai_model', 'status_correct'], name='completenes_ai_mode_c971c0_idx'), models.Index(fields=['prediction_confidence', 'score_accuracy'], name='completenes_predict_d2d325_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompletenessTestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_timestamp', models.DateTimeField(auto_now_add=True, help_text='When the completeness test was performed')),
                ('engagement_id', models.CharField(help_text='Engagement ID for cross-referencing TB data', max_length=100)),
                ('overall_status', models.CharField(choices=[('PASS', 'All tests passed'), ('FAIL', 'One or more tests failed'), ('TB_NOT_AVAILABLE', 'Trial Balance data not available'), ('ERROR', 'Error during testing')], help_text='Overall test result', max_length=20)),
                ('overall_explanation', models.TextField(help_text='Detailed explanation of the test result')),
                ('completeness_score', models.FloatField(help_text='Overall completeness score (0-100%)')),
                ('step1_gl_tb_reconciliation', models.JSONField(default=dict, help_text='GL-TB reconciliation test results')),
                ('step2_debit_credit_balance', models.JSONField(default=dict, help_text='Debit-credit balance verification results')),
                ('step3_account_coverage', models.JSONField(default=dict, help_text='Account coverage analysis results')),
                ('step4_transaction_gaps', models.JSONField(default=dict, help_text='Transaction gap detection results')),
                ('total_gl_records', models.IntegerField(help_text='Total GL posting records analyzed')),
                ('total_tb_records', models.IntegerField(blank=True, help_text='Total TB records (if available)', null=True)),
                ('tests_passed', models.IntegerField(help_text='Number of tests passed')),
                ('total_tests', models.IntegerField(help_text='Total number of tests performed')),
                ('anomalies_detected', models.JSONField(default=list, help_text='List of detected anomalies and gaps')),
                ('critical_issues_count', models.IntegerField(default=0, help_text='Number of critical issues found')),
                ('comprehensive_statistics', models.JSONField(default=dict, help_text='Comprehensive GL statistics including document stats, subtype analysis, user analysis, and monthly trends')),
                ('processing_duration', models.FloatField(help_text='Test processing duration in seconds')),
                ('data_file', models.ForeignKey(help_text='Reference to the GL data file', on_delete=django.db.models.deletion.CASCADE, related_name='completeness_tests', to='core.datafile')),
            ],
            options={
                'db_table': 'completeness_test_results',
                'ordering': ['-test_timestamp'],
                'indexes': [models.Index(fields=['data_file', 'test_timestamp'], name='completenes_data_fi_1b3af9_idx'), models.Index(fields=['engagement_id', 'overall_status'], name='completenes_engagem_e3a279_idx'), models.Index(fields=['overall_status', 'completeness_score'], name='completenes_overall_652f91_idx'), models.Index(fields=['test_timestamp'], name='completenes_test_ti_852604_idx')],
            },
        ),
    ]
