# Generated by Django 5.2.4 on 2025-09-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_chart_of_accounts_unique_constraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='chart_of_ac_data_fi_5d57b4_idx',
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('account', 'cost_center')},
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['account', 'cost_center'], name='chart_of_ac_account_42b61a_idx'),
        ),
    ]
