# Generated by Django 5.2.4 on 2025-09-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_data_file_from_coa_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together=set(),
        ),
    ]
