# Generated by Django 5.2.4 on 2025-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_chart_of_accounts_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account',
            field=models.CharField(help_text='Account Code (no decimal values allowed)', max_length=20),
        ),
    ]
