# Generated by Django 5.2.4 on 2025-09-21 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_gl_prediction_model_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profit_center_code', models.CharField(db_index=True, help_text='Unique Profit Center Code (normalized)', max_length=10, unique=True)),
                ('profit_center_name', models.CharField(help_text='Profit Center Name/Description', max_length=200)),
                ('profit_center_short_text', models.CharField(blank=True, help_text='Short Profit Center Text', max_length=50)),
                ('profit_center_type', models.CharField(blank=True, db_index=True, help_text='Profit Center Type (e.g., Sales, Production, Service, Administrative)', max_length=50)),
                ('profit_center_group', models.CharField(blank=True, db_index=True, help_text='Profit Center Group (e.g., Revenue Centers, Cost Centers)', max_length=50)),
                ('revenue_center', models.BooleanField(db_index=True, default=False, help_text='Is this a Revenue Center?')),
                ('cost_center', models.BooleanField(db_index=True, default=True, help_text='Is this a Cost Center? (default True as most profit centers are cost centers)')),
                ('profit_center_currency', models.CharField(default='SAR', help_text='Profit Center Currency', max_length=3)),
                ('profit_center_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], db_index=True, default='ACTIVE', help_text='Profit Center Status', max_length=20)),
                ('profit_center_level', models.IntegerField(default=1, help_text='Profit Center Level in hierarchy (1=top level)')),
                ('company_code', models.CharField(blank=True, db_index=True, help_text='Company Code', max_length=10)),
                ('business_area', models.CharField(blank=True, db_index=True, help_text='Business Area', max_length=10)),
                ('segment', models.CharField(blank=True, db_index=True, help_text='Segment', max_length=10)),
                ('responsible_person', models.CharField(blank=True, help_text='Responsible Person/Manager', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department', max_length=100)),
                ('profit_center_description', models.TextField(blank=True, help_text='Detailed Profit Center Description')),
                ('notes', models.TextField(blank=True, help_text='Additional Notes')),
                ('created_from_file', models.ForeignKey(blank=True, help_text='Data file that created this profit center', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datafile')),
                ('last_updated_from_file', models.ForeignKey(blank=True, help_text='Data file that last updated this profit center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_profit_centers', to='core.datafile')),
                ('parent_profit_center', models.ForeignKey(blank=True, help_text='Parent Profit Center (for hierarchical structure)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profit_centers', to='core.profitcenter')),
            ],
            options={
                'db_table': 'profit_centers',
                'ordering': ['profit_center_code'],
            },
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='profit_center_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to Profit Center master record (cost_center field maps to profit center)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chart_of_accounts', to='core.profitcenter'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='profit_center_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to Profit Center master record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_postings', to='core.profitcenter'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['profit_center_code'], name='profit_cent_profit__4f8f81_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['profit_center_type'], name='profit_cent_profit__d8a2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['profit_center_group'], name='profit_cent_profit__7d20e7_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['revenue_center'], name='profit_cent_revenue_1b2929_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['cost_center'], name='profit_cent_cost_ce_7248e9_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['profit_center_status'], name='profit_cent_profit__94d59f_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['company_code'], name='profit_cent_company_5a20ab_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['business_area'], name='profit_cent_busines_f2e62a_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['segment'], name='profit_cent_segment_c09902_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenter',
            index=models.Index(fields=['parent_profit_center'], name='profit_cent_parent__ad69ab_idx'),
        ),
    ]
