# Generated by Django 5.2.4 on 2025-09-21 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_profit_center_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitCenterAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary profit center for this account?')),
                ('allocation_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Allocation percentage for this profit center-account relationship', max_digits=5, null=True)),
                ('company_code', models.CharField(blank=True, help_text='Company Code for this relationship', max_length=10)),
                ('business_area', models.CharField(blank=True, help_text='Business Area for this relationship', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this relationship')),
                ('gl_account', models.ForeignKey(help_text='GL Account', on_delete=django.db.models.deletion.CASCADE, to='core.glaccount')),
                ('profit_center', models.ForeignKey(help_text='Profit Center', on_delete=django.db.models.deletion.CASCADE, to='core.profitcenter')),
            ],
            options={
                'db_table': 'profit_center_accounts',
            },
        ),
        migrations.AddField(
            model_name='profitcenter',
            name='gl_accounts',
            field=models.ManyToManyField(blank=True, help_text='GL Accounts associated with this profit center', related_name='profit_centers', through='core.ProfitCenterAccount', to='core.glaccount'),
        ),
        migrations.AddIndex(
            model_name='profitcenteraccount',
            index=models.Index(fields=['profit_center', 'gl_account'], name='profit_cent_profit__4a12fa_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenteraccount',
            index=models.Index(fields=['is_primary'], name='profit_cent_is_prim_f98f80_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenteraccount',
            index=models.Index(fields=['company_code'], name='profit_cent_company_8de351_idx'),
        ),
        migrations.AddIndex(
            model_name='profitcenteraccount',
            index=models.Index(fields=['business_area'], name='profit_cent_busines_a8d85c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profitcenteraccount',
            unique_together={('profit_center', 'gl_account')},
        ),
    ]
