# Generated by Django 5.2.4 on 2025-09-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_profit_center_account_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glaccount',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='glaccount',
            name='profit_center',
        ),
        migrations.AddField(
            model_name='glaccount',
            name='cost_code',
            field=models.CharField(blank=True, db_index=True, help_text='Cost Code (maps to Profit Center from GL listing)', max_length=10),
        ),
        migrations.AddField(
            model_name='glaccount',
            name='profit_center_ref',
            field=models.ForeignKey(blank=True, help_text='Reference to Profit Center master record (cost_code field maps to profit center)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_gl_accounts', to='core.profitcenter'),
        ),
    ]
