# Generated by Django 5.2.4 on 2025-09-21 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_restructure_gl_account_cost_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='engagement',
            field=models.ForeignKey(help_text='Engagement this account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gl_accounts', to='core.engagement'),
        ),
    ]
