# Generated by Django 5.2.4 on 2025-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_engagement_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='completenesstestresult',
            name='data_version',
            field=models.CharField(default='1.0', help_text='Version of the data files used in this test (e.g., 1.0, 1.1, 2.0)', max_length=20),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='version_notes',
            field=models.TextField(blank=True, help_text='Notes about this test version (changes, updates, etc.)'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='version',
            field=models.CharField(default='1.0', help_text='Version of the file (e.g., 1.0, 1.1, 2.0)', max_length=20),
        ),
        migrations.AddField(
            model_name='datafile',
            name='version_notes',
            field=models.TextField(blank=True, help_text='Notes about this version (changes, updates, etc.)'),
        ),
    ]
