# Generated by Django 5.2.4 on 2025-09-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_version_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='parent_engagement',
            field=models.ForeignKey(blank=True, help_text='Parent engagement for version tracking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_versions', to='core.engagement'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='version',
            field=models.CharField(default='1.0', help_text='Version of the engagement (e.g., 1.0, 1.1, 2.0)', max_length=20),
        ),
        migrations.AddField(
            model_name='engagement',
            name='version_notes',
            field=models.TextField(blank=True, help_text='Notes about this engagement version (changes, updates, etc.)'),
        ),
    ]
