# Generated by Django 5.2.4 on 2025-09-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_engagement_version_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='parent_engagement',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='version',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='version_notes',
        ),
        migrations.AlterField(
            model_name='completenesstestresult',
            name='data_version',
            field=models.CharField(db_index=True, default='1.0', help_text='Version of the data files used in this test (e.g., 1.0, 1.1, 2.0) - allows multiple test runs per engagement', max_length=20),
        ),
        migrations.AlterField(
            model_name='completenesstestresult',
            name='version_notes',
            field=models.TextField(blank=True, help_text='Notes about this test version (retry reasons, fixes applied, etc.)'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='version',
            field=models.CharField(db_index=True, default='1.0', help_text='Version of the file (e.g., 1.0, 1.1, 2.0) - allows multiple test versions per engagement', max_length=20),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='version_notes',
            field=models.TextField(blank=True, help_text='Notes about this version (changes, updates, retry reasons, etc.)'),
        ),
        migrations.AddIndex(
            model_name='completenesstestresult',
            index=models.Index(fields=['engagement', 'data_version'], name='completenes_engagem_534720_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['engagement', 'version'], name='data_files_engagem_13fc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=models.Index(fields=['engagement', 'file_type', 'version'], name='data_files_engagem_871644_idx'),
        ),
    ]
