# Generated by Django 5.2.4 on 2025-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_engagement_version_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='completenesstestresult',
            name='average_document_variance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average variance per document', max_digits=20),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='balanced_documents',
            field=models.IntegerField(default=0, help_text='Number of balanced documents'),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='document_balance_rate',
            field=models.FloatField(default=0.0, help_text='Percentage of balanced documents'),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='no_document_transaction_count',
            field=models.IntegerField(default=0, help_text='Count of transactions with no document numbers'),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='total_document_variance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total variance across all documents', max_digits=20),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='total_documents',
            field=models.IntegerField(default=0, help_text='Total number of documents found'),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='transactions_with_documents',
            field=models.IntegerField(default=0, help_text='Number of transactions with document numbers'),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='transactions_without_documents',
            field=models.IntegerField(default=0, help_text='Number of transactions without document numbers'),
        ),
        migrations.AddField(
            model_name='completenesstestresult',
            name='unbalanced_documents',
            field=models.IntegerField(default=0, help_text='Number of unbalanced documents'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='financial_statement',
            field=models.CharField(blank=True, help_text='Financial Statement (from Chart of Accounts)', max_length=50),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='gl_account_long_text',
            field=models.CharField(blank=True, help_text='GL Account Long Text (from Chart of Accounts)', max_length=200),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='gl_account_sub_sub_type',
            field=models.CharField(blank=True, db_index=True, help_text='GL Account Sub Sub Type (from Chart of Accounts)', max_length=50),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='gl_account_sub_type',
            field=models.CharField(blank=True, db_index=True, help_text='GL Account Sub Type (from Chart of Accounts)', max_length=50),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='gl_account_type',
            field=models.CharField(blank=True, db_index=True, help_text='GL Account Type (from Chart of Accounts)', max_length=50),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='ref_to_fs',
            field=models.CharField(blank=True, help_text='Reference to Financial Statement (from Chart of Accounts)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='sapglposting',
            index=models.Index(fields=['gl_account_type'], name='sap_gl_post_gl_acco_116b62_idx'),
        ),
        migrations.AddIndex(
            model_name='sapglposting',
            index=models.Index(fields=['gl_account_sub_type'], name='sap_gl_post_gl_acco_894376_idx'),
        ),
        migrations.AddIndex(
            model_name='sapglposting',
            index=models.Index(fields=['gl_account_sub_sub_type'], name='sap_gl_post_gl_acco_596755_idx'),
        ),
        migrations.AddIndex(
            model_name='sapglposting',
            index=models.Index(fields=['financial_statement'], name='sap_gl_post_financi_0b5772_idx'),
        ),
    ]
