# Generated by Django 5.2.4 on 2025-09-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_document_verification_and_gl_account_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='local_file_path',
            field=models.CharField(blank=True, help_text='Local file path where file is saved', max_length=500),
        ),
    ]
