# Generated by Django 5.2.4 on 2025-09-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_local_file_path_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glaccount',
            name='account_code',
            field=models.CharField(db_index=True, help_text='GL Account Code (no decimal or fractional values allowed)', max_length=50),
        ),
    ]
