# Generated by Django 5.2.4 on 2025-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_increase_account_code_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapglposting',
            name='gl_account',
            field=models.CharField(db_index=True, help_text='G/L Account (legacy field, no decimal values allowed)', max_length=50),
        ),
    ]
