# Generated by Django 5.2.4 on 2025-09-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_increase_gl_account_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapglposting',
            name='offsetting_account',
            field=models.CharField(blank=True, help_text='Offsetting Account', max_length=50),
        ),
    ]
