# Generated by Django 5.2.4 on 2025-09-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_increase_offsetting_account_length'),
    ]

    operations = [
        # Add missing fields that are causing the bulk loading to fail
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS document_type VARCHAR(10) DEFAULT '';",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS document_type;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS invoice_reference VARCHAR(20) DEFAULT '';",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS invoice_reference;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS clearing_document VARCHAR(20) DEFAULT '';",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS clearing_document;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS sales_document VARCHAR(20) DEFAULT '';",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS sales_document;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS assignment VARCHAR(20) DEFAULT '';",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS assignment;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS text VARCHAR(100) DEFAULT '';",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS text;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS year_month VARCHAR(7) DEFAULT '';",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS year_month;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS document_date DATE;",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS document_date;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS entry_date DATE;",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS entry_date;"
        ),
        migrations.RunSQL(
            "ALTER TABLE core_sapglposting ADD COLUMN IF NOT EXISTS posting_period INTEGER DEFAULT 1;",
            reverse_sql="ALTER TABLE core_sapglposting DROP COLUMN IF EXISTS posting_period;"
        ),
    ]
