# Generated by Django 5.2.4 on 2025-09-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_increase_offsetting_account_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapglposting',
            name='document_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Document Type', max_length=10),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='document_date',
            field=models.DateField(blank=True, db_index=True, help_text='Document Date', null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='entry_date',
            field=models.DateField(blank=True, db_index=True, help_text='Entry Date', null=True),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='posting_period',
            field=models.IntegerField(db_index=True, help_text='Posting Period'),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='text',
            field=models.CharField(blank=True, help_text='Text', max_length=100),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='clearing_document',
            field=models.CharField(blank=True, help_text='Clearing Document', max_length=20),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='invoice_reference',
            field=models.CharField(blank=True, help_text='Invoice Reference', max_length=20),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='sales_document',
            field=models.CharField(blank=True, help_text='Sales Document', max_length=20),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='assignment',
            field=models.CharField(blank=True, help_text='Assignment', max_length=20),
        ),
        migrations.AddField(
            model_name='sapglposting',
            name='year_month',
            field=models.CharField(blank=True, help_text='Year/Month', max_length=7),
        ),
    ]
