# Generated by Django 5.2.4 on 2025-09-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_missing_fields_manual'),
        ('core', '0025_add_missing_sapglposting_fields'),
    ]

    operations = [
    ]
