# Generated by Django 5.2.4 on 2025-09-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20250928_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sapglposting',
            name='asset_number',
            field=models.CharField(blank=True, help_text='Asset Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='assignment',
            field=models.CharField(blank=True, help_text='Assignment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='business_area',
            field=models.CharField(blank=True, help_text='Business Area', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='clearing_document',
            field=models.CharField(blank=True, help_text='Clearing Document', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='company_code',
            field=models.CharField(blank=True, help_text='Company Code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost Center', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='document_header_text',
            field=models.CharField(blank=True, help_text='Document Header Text', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='financial_statement',
            field=models.CharField(blank=True, help_text='Financial Statement (from Chart of Accounts)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='gl_account_long_text',
            field=models.CharField(blank=True, help_text='GL Account Long Text (from Chart of Accounts)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='gl_account_sub_sub_type',
            field=models.CharField(blank=True, db_index=True, help_text='GL Account Sub Sub Type (from Chart of Accounts)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='gl_account_sub_type',
            field=models.CharField(blank=True, db_index=True, help_text='GL Account Sub Type (from Chart of Accounts)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='gl_account_type',
            field=models.CharField(blank=True, db_index=True, help_text='GL Account Type (from Chart of Accounts)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='invoice_reference',
            field=models.CharField(blank=True, help_text='Invoice Reference', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='offsetting_account',
            field=models.CharField(blank=True, help_text='Offsetting Account', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='order_number',
            field=models.CharField(blank=True, help_text='Order Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='partner_business_area',
            field=models.CharField(blank=True, help_text='Partner Business Area', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='posting_key',
            field=models.CharField(blank=True, help_text='Posting Key', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='ref_to_fs',
            field=models.CharField(blank=True, help_text='Reference to Financial Statement (from Chart of Accounts)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='reference_document',
            field=models.CharField(blank=True, help_text='Reference Document', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='sales_document',
            field=models.CharField(blank=True, help_text='Sales Document', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='segment',
            field=models.CharField(blank=True, db_index=True, help_text='Segment', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='sub_number',
            field=models.CharField(blank=True, help_text='Sub Number', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='text',
            field=models.CharField(blank=True, help_text='Text', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='transaction_currency',
            field=models.CharField(blank=True, help_text='Transaction currency code', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='wbs_element',
            field=models.CharField(blank=True, help_text='WBS Element', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sapglposting',
            name='year_month',
            field=models.CharField(blank=True, help_text='Year/Month', max_length=7, null=True),
        ),
    ]
