# Generated by Django 5.2.4 on 2025-09-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_null_true_to_charfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(blank=True, help_text='Code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='company',
            field=models.CharField(blank=True, help_text='Company', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='cost_center',
            field=models.CharField(blank=True, help_text='Cost Center', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='financial_statement',
            field=models.CharField(blank=True, help_text='Financial Statement', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='gl_account_long_text',
            field=models.CharField(blank=True, help_text='G/L Account Long Text', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='ref_to_fs',
            field=models.CharField(blank=True, help_text='Reference to Financial Statement', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='ref_to_note',
            field=models.CharField(blank=True, help_text='Reference to Note', max_length=20, null=True),
        ),
    ]
